version: '3.7'

services:
  
  db:
    image: postgres:12
    env_file: 
      .db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis
  
  backend:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: >- 
      bash -c "python manage.py makemigrations &&
      python manage.py makemigrations interface && 
      python manage.py migrate --noinput && 
      python manage.py migrate --noinput interface && 
      python manage.py collectstatic --no-input &&
      python manage.py loaddata /backend/language_models.json &&
      gunicorn judge.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - app:/backend:rw
      - static:/backend/static/
      - media:/backend/media/
    env_file: 
      - .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  
  executor:
    image: phantsure/oj:latest
    depends_on:
      - redis
      - db 
      - backend

  celery:
    build: .
    command: celery -A judge worker -l info
    volumes:
      - .:/backend
    depends_on:
      - redis
      - db
      - backend

volumes:
  postgres_data:
  app:
  media:
  static: